apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jenkins
  namespace: jenkins
spec:
  serviceName: jenkins-service
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      serviceAccountName: jenkins-admin
      containers:
        - name: jenkins
          image: jenkins/jenkins:jdk21
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
            - name: binary
              mountPath: /usr/bin
      volumes:
        - name: binary
          hostPath:
            path: /usr/bin
            type: Directory
  volumeClaimTemplates:
    - metadata:
        name: jenkins-home
      spec:
        accessModes:
          - ReadWriteMany           # Adjust based on your storage class support
        storageClassName: pv-storage    # Modify per your cluster's storage class
        resources:
          requests:
            storage: 20Gi
